version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: council-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'your_strong_root_password' # 请替换为强密码
      MYSQL_DATABASE: 'parliament_loop'
      MYSQL_USER: 'council_user'
      MYSQL_PASSWORD: 'parliament_pass_2024' # 保持与.env.example一致
    ports:
      - "3307:3306" # 外部端口3307映射到容器内部3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
